export const data = [
    {
      "_id": "5f75ee32a0c05042bca7f63b",
      "index": 0,
      "isActive": true,
      "balance": "$3,243.16",
      "picture": "http://placehold.it/32x32",
      "age": 34,
      "eyeColor": "green",
      "name": "Alyson Britt",
      "gender": "female",
      "company": "TROLLERY",
      "email": "alysonbritt@trollery.com",
      "phone": "+1 (818) 440-2886",
      "address": "336 Kay Court, Sharon, Texas, 1521",
      "about": "Sunt pariatur voluptate elit eu ea proident nostrud aute consequat ad commodo. Officia labore ad adipisicing incididunt deserunt officia esse reprehenderit veniam eu incididunt et ullamco do. Non consequat dolore quis id est non non quis Lorem. Aliqua consectetur mollit nulla cillum magna. Veniam sint adipisicing proident id ex proident dolor exercitation aliquip ad do ut. Sunt eiusmod ad incididunt voluptate occaecat enim mollit. Sunt minim consectetur voluptate et commodo adipisicing ad et ut incididunt occaecat ex consectetur.\r\n",
      "registered": "2014-11-19T07:07:43 +03:00",
      "latitude": 57.638652,
      "longitude": 172.866185
    },
    {
      "_id": "5f75ee32df562d08527d1036",
      "index": 1,
      "isActive": true,
      "balance": "$1,777.10",
      "picture": "http://placehold.it/32x32",
      "age": 21,
      "eyeColor": "brown",
      "name": "Sandy Head",
      "gender": "female",
      "company": "VIAGRAND",
      "email": "sandyhead@viagrand.com",
      "phone": "+1 (802) 555-3764",
      "address": "889 Morgan Avenue, Eastmont, North Dakota, 5324",
      "about": "Mollit consequat Lorem dolore sit cillum nisi enim irure irure consectetur. Tempor quis amet cillum in dolor consectetur nulla ut consequat consectetur. Quis ea sit nulla labore eu in consectetur id quis culpa. Esse minim nulla minim non fugiat Lorem sunt aliqua laboris irure Lorem ipsum. Officia excepteur aute in reprehenderit adipisicing. Incididunt cillum cupidatat laborum occaecat esse nulla consectetur ad aliquip est incididunt do eiusmod.\r\n",
      "registered": "2015-10-07T11:48:24 +03:00",
      "latitude": -18.920765,
      "longitude": 2.199439
    },
    {
      "_id": "5f75ee324829fc265d32f47b",
      "index": 2,
      "isActive": true,
      "balance": "$1,015.01",
      "picture": "http://placehold.it/32x32",
      "age": 31,
      "eyeColor": "blue",
      "name": "Alfreda Mckay",
      "gender": "female",
      "company": "NURPLEX",
      "email": "alfredamckay@nurplex.com",
      "phone": "+1 (936) 466-2238",
      "address": "727 Vernon Avenue, Fresno, Rhode Island, 6808",
      "about": "Consectetur fugiat anim aute aliqua dolor elit. Laborum elit laborum labore elit. Reprehenderit mollit ea id qui fugiat reprehenderit consequat aute.\r\n",
      "registered": "2017-03-31T02:30:43 +03:00",
      "latitude": -33.186368,
      "longitude": -173.080066
    },
    {
      "_id": "5f75ee320c7f26af8f3695a7",
      "index": 3,
      "isActive": false,
      "balance": "$1,164.10",
      "picture": "http://placehold.it/32x32",
      "age": 39,
      "eyeColor": "brown",
      "name": "Greer Noble",
      "gender": "male",
      "company": "BYTREX",
      "email": "greernoble@bytrex.com",
      "phone": "+1 (884) 412-3241",
      "address": "217 Cypress Court, Templeton, New Jersey, 6772",
      "about": "Aute dolore esse id nisi aute ullamco Lorem ad sunt tempor sint. Esse irure non sint fugiat do nostrud. Labore id tempor irure nulla aute reprehenderit ipsum nulla amet fugiat nostrud culpa. Do et eu occaecat adipisicing amet consectetur voluptate aute voluptate cupidatat. Velit officia cillum sint nisi elit. Sint nulla magna incididunt et sit pariatur ad officia qui reprehenderit aute quis.\r\n",
      "registered": "2014-03-03T01:42:31 +03:00",
      "latitude": 78.662909,
      "longitude": 50.996145
    },
    {
      "_id": "5f75ee327b8b3cfc2edeea9c",
      "index": 4,
      "isActive": false,
      "balance": "$2,266.78",
      "picture": "http://placehold.it/32x32",
      "age": 25,
      "eyeColor": "blue",
      "name": "Lancaster Bowers",
      "gender": "male",
      "company": "AMTAS",
      "email": "lancasterbowers@amtas.com",
      "phone": "+1 (839) 561-3128",
      "address": "679 Narrows Avenue, Campo, Utah, 2781",
      "about": "Quis quis dolore ipsum magna. Ad irure quis labore enim nisi ea esse dolor minim enim. Esse ullamco ullamco laboris Lorem quis Lorem proident eiusmod ad Lorem et. Proident nostrud exercitation sunt consequat et mollit laborum ullamco mollit aliqua.\r\n",
      "registered": "2018-06-19T04:00:54 +03:00",
      "latitude": -70.257682,
      "longitude": 98.544722
    },
    {
      "_id": "5f75ee32563ece81b318c78d",
      "index": 5,
      "isActive": true,
      "balance": "$3,610.46",
      "picture": "http://placehold.it/32x32",
      "age": 26,
      "eyeColor": "green",
      "name": "Suarez Logan",
      "gender": "male",
      "company": "TERRAGEN",
      "email": "suarezlogan@terragen.com",
      "phone": "+1 (967) 472-2281",
      "address": "660 Goodwin Place, Cetronia, Colorado, 7866",
      "about": "Nisi ipsum occaecat voluptate veniam. Deserunt excepteur esse minim id ipsum occaecat ullamco et. Reprehenderit esse aliqua sit ad voluptate adipisicing amet proident incididunt.\r\n",
      "registered": "2014-12-01T03:42:13 +03:00",
      "latitude": -72.332489,
      "longitude": 101.28433
    }
  ]